name: C/C++ CI

on:
  push:
    branches: [ "main", "devel", "otus_4" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gtest
      run: sudo apt-get install -y libgtest-dev libgmock-dev
    - uses: actions/checkout@v4

    - name: Create generator
      run: mkdir build-gen; cd build-gen; cmake ../generator; make;

    - name: Create classes
      run: build-gen; ./generator ../ifaces ../include;

    - name: configure
      run: mkdir build; cd build; cmake ..;
    - name: make
      run: cd build;make;
    - name: test
      run: cd build;make test;
    - name: execute
      run: cd build;./battlefield;
